### PR TITLE
Upgrades dependencies to laravel 6

### PR DESCRIPTION
**Pull request by eduarguz**
Hi, I am not sure how would you go when supporting laravel 6. I can help if you have a better solution.

For now, it will drop support for laravel 5.x and set defaults to support laravel 6. Let me know what you think or how will you go about this.

### CODE REVIEW

**Comment by Jeroen-G** [comment]
If you could work on these, that would be great:
- [ ] Test on php 7.3 as well
- [ ] Support both Laravel 5 and 6 for the time being, let the package creator choose to drop 5.

**Comment by eduarguz** [comment]
Updated.
I *think* this should work...

**Comment by Jeroen-G** [comment]
You can test it with Laravel Packager by going to [its config file](https://github.com/Jeroen-G/laravel-packager/blob/master/config/packager.php) and setting the skeleton url to `https://github.com/eduarguz/packager-skeleton/archive/feature/support-l6.zip` and then run `php artisan packager:new Shiny Package`

**Comment by Jeroen-G** [comment]
@eduarguz Did you give it a try?

**Pull request merged**
